import { step } from './utils';
import type { ElectionStep } from '@/types';

export const JP_BEGINNER: ElectionStep[] = [
  step('jp-1', 1, 'Eligibility Check', 'Ensure you meet the basic requirements to vote in Japan.',
    'You must be a Japanese citizen and 18 years of age or older. For local elections, you must also have lived in the relevant municipality for at least three months.',
    'Be a citizen, 18+, and live in your area for 3 months.',
    'Ongoing',
    ['Japanese citizenship', 'Age 18+'],
    ['Check your local municipal office if you recently moved.'],
    'What is the minimum age to vote in Japan?', ['16', '18', '20', '21'], 1, 'The age was lowered from 20 to 18 in 2016.'),
  step('jp-2', 2, 'Voter Notification', 'Receive your voting ticket (tōhyō-ken) by mail.',
    'A voting ticket is sent to your registered address before the election. This ticket indicates your designated polling station.',
    'Watch for a voting ticket in your mail.',
    '1-2 weeks before election',
    ['Valid residential registration'],
    ['If you lose your ticket, you can still vote by showing ID at the polling station.'],
    'What is the voting ticket called in Japanese?', ['Tōhyō-ken', 'Pass-pōto', 'Menkyo-shō', 'Kard-o'], 0, 'Tōhyō-ken literally means voting ticket.'),
  step('jp-3', 3, 'Polling Station Procedure', 'Visit your assigned station on election day.',
    'Present your ticket, receive your ballot, and write the name of the candidate or party in the private booth.',
    'Go to your station, get a ballot, and write your choice.',
    'Election Day (7 AM - 8 PM)',
    ['Voting ticket (optional but recommended)'],
    ['Japan uses a unique "write-in" system; ensure you know the spelling of your choice.'],
    'How do you mark your choice on the ballot?', ['Checkmark', 'X', 'Write the name', 'Punch a hole'], 2, 'Japan uses a handwritten ballot system.'),
];

export const ZA_BEGINNER: ElectionStep[] = [
  step('za-1', 1, 'Voter Registration', 'Register on the national common voters\' roll.',
    'You must be a South African citizen, at least 16 years old (to register), and have a green barcoded ID book, smart ID card, or temporary identity certificate.',
    'Register with your ID if you are 16+.',
    'Ongoing (Registration weekends specifically announced)',
    ['SA ID document', 'South African citizenship'],
    ['You can check your registration status online or via SMS.'],
    'What is the minimum age to register to vote?', ['14', '16', '18', '21'], 1, 'You can register at 16 but vote only at 18.'),
  step('za-2', 2, 'Find Your Voting Station', 'Identify where you need to cast your vote.',
    'You must vote at the station where you are registered, unless you have notified the IEC of a "Section 24A" move.',
    'Vote where you registered.',
    'Before Election Day',
    ['Registration confirmation'],
    ['The IEC "Locate My Station" tool is very helpful.'],
    'Where are you normally required to vote?', ['Any station', 'Where you registered', 'At the police station', 'Online'], 1, 'Registration is station-specific in SA.'),
  step('za-3', 3, 'Casting Your Vote', 'Visit the station and mark your three ballots.',
    'Voters usually receive three ballots: National, Regional, and Provincial. Mark with an "X" in the box next to your choice.',
    'Go to the station and mark "X" on your ballots.',
    'Election Day (7 AM - 9 PM)',
    ['SA ID document'],
    ['Your thumb will be marked with indelible ink after voting.'],
    'How many ballots do voters usually receive?', ['One', 'Two', 'Three', 'Four'], 2, 'National, Regional, and Provincial ballots.'),
];

